development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: clubber
  pool: 5
  username: root
  password: '123456'

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: clubber_test
  pool: 5
  username: root
  password:

production:
  adapter: sqlite3
  database: db/production
  pool: 5
  timeout: 5000
